import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
a=smtplib.SMTP('smtp.gmail.com',587)
a.ehlo()
a.starttls()
body="Attached file is your Expense Report generated By MY MONEY BANK Software.\n \nThis is automatically generated mail.\nPlease, do not reply."

msgeg=MIMEMultipart()
msgeg['From']="MY MONEY BANK <'sender mail'>"#SENDER
msgeg['Subject']='Monthly Expense Report '
msgeg.attach(MIMEText(body,'plain'))

filename=name+".pdf"
attachment=open(name+".pdf","rb")
p= MIMEBase('application','octet-stream')
p.set_payload((attachment).read())
encoders.encode_base64(p)
p.add_header('Content-Disposition',"attachment; filename= %s"%filename)
msgeg.attach(p)
text=msgeg.as_string()
reciever=email_user
sender='sender mail'
a.login('sender mail','password')

a.sendmail(sender,reciever,text)
print("Successfully Sent File")
a.quit()
